services:
  - type: web
    name: bharat-social-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      # Database credentials will be set in Render dashboard
      # SPRING_DATASOURCE_URL
      # SPRING_DATASOURCE_USERNAME  
      # SPRING_DATASOURCE_PASSWORD

  - type: web
    name: bharat-social-frontend
    env: docker
    plan: free
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: bharat-social-backend
          property: host
    # Add health check for better deployment reliability
    healthCheckPath: /

