services:
  - type: web
    name: bharat-social-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: social-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: social-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: social-db
          property: password

  - type: web
    name: bharat-social-frontend
    env: docker
    plan: free
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: bharat-social-backend
          property: host

databases:
  - name: social-db
    plan: free
    databaseName: social
