services:
  - type: web
    name: bharat-social-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/bharat-social-media-backend-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: social-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: social-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: social-db
          property: password

databases:
  - name: social-db
    plan: free
    databaseName: social
